### ISSUE TITLE
I cannot transform an empty array, I get an exception but would expect an empty array

### ISSUE THREAD

**Issue by kirchsth** [WorkMaze/JUST.net#159]
related to #155 (and maybe #113 too)

I cannot transform an empty array, I get an exception but would expect an empty array.

input file
```
{ "Systems": [ ] }
```
transformation file
```
{ "systemIds" : [ "#valueof($.Systems[:].Id)" ] }
```
expected transformed file
```
{"systemIds":[ ]}
```

but following exception was thrown
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'o')
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(Object value, String parameterName)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.FromObject(Object o)
   at JUST.JsonTransformer`1.BuildArrayToken(JArray arrayToken, IEnumerable`1 itemsToAdd)
   at JUST.JsonTransformer`1.RecursiveEvaluate(JToken parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken)
   at JUST.JsonTransformer`1.RecursiveEvaluate(JToken parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken)
   at JUST.JsonTransformer`1.Transform(JObject transformer, JToken input)
   at JUST.JsonTransformer`1.Transform(String transformerJson, JToken input)
   at JUST.JsonTransformer`1.Transform(String transformerJson, String inputJson)
   at JsonConversion.JUSTOpenTests.ConvertEmptyArrays() in C:\Users\KIRCHSTH\source\repos\JsonConversion\JsonConversion\JUSTOpenTests.cs:line 245
```

Thank you and best regards
Helmut

PS.: If I have one item in the array its working fine:

input file 

```
{ "Systems": [ { "Id": "SystemId1" } ] }
```

transformed file
```
{"systemIds":["SystemId1"]}
```

**Comment by Courela** [comment]
It is trying to add a null value to array, instead of returning an empty array. I'll make a pull request to fix this.

**Comment by kirchsth** [comment]
Thank you for the fast fix.
BR Helmut
