### ISSUE TITLE
Access to scope alias is being lost in nested loop

### ISSUE THREAD

**Issue by vmello-esw** [WorkMaze/JUST.net#234]
Hi,

I'm receiving a `key X was not present in the dictionary` exception when I try to execute the following transformation, is there anything wrong with the transformation ?

**Package Version**: `4.2.1`

Exception: 
```
System.Exception
  HResult=0x80131500
  Message=Error while calling function : #currentvalue(affectedItems) - The given key 'affectedItems' was not present in the dictionary.
  Source=JUST.net
  StackTrace:
   at JUST.JsonTransformer`1.ParseFunction(String functionString, IDictionary`2 array, IDictionary`2 currentArrayElement)
   at JUST.JsonTransformer`1.ParseToken(JToken parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken, List`1& selectedTokens, Dictionary`2& tokensToReplace, List`1& tokensToDelete, List`1& loopProperties, List`1& condProps, JArray& arrayToForm, JObject& dictToForm, List`1& tokenToForm, List`1& tokensToAdd, Boolean& isLoop, Boolean& isBulk, JToken childToken)
   at JUST.JsonTransformer`1.RecursiveEvaluate(JToken& parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken)
   at JUST.JsonTransformer`1.ParseToken(JToken parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken, List`1& selectedTokens, Dictionary`2& tokensToReplace, List`1& tokensToDelete, List`1& loopProperties, List`1& condProps, JArray& arrayToForm, JObject& dictToForm, List`1& tokenToForm, List`1& tokensToAdd, Boolean& isLoop, Boolean& isBulk, JToken childToken)
   at JUST.JsonTransformer`1.RecursiveEvaluate(JToken& parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken)
   at JUST.JsonTransformer`1.LoopOperation(String propertyName, String arguments, IDictionary`2 parentArray, IDictionary`2 currentArrayToken, List`1& loopProperties, JArray& arrayToForm, JObject& dictToForm, JToken childToken)
   at JUST.JsonTransformer`1.ParsePropertyFunction(IDictionary`2 parentArray, IDictionary`2 currentArrayToken, List`1& loopProperties, List`1& condProps, JArray& arrayToForm, JObject& dictToForm, List`1& tokenToForm, List`1& tokensToAdd, Boolean& isLoop, JToken childToken, JProperty property, String functionName, String arguments)
   at JUST.JsonTransformer`1.ParseToken(JToken parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken, List`1& selectedTokens, Dictionary`2& tokensToReplace, List`1& tokensToDelete, List`1& loopProperties, List`1& condProps, JArray& arrayToForm, JObject& dictToForm, List`1& tokenToForm, List`1& tokensToAdd, Boolean& isLoop, Boolean& isBulk, JToken childToken)
   at JUST.JsonTransformer`1.RecursiveEvaluate(JToken& parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken)
   at JUST.JsonTransformer`1.ParseToken(JToken parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken, List`1& selectedTokens, Dictionary`2& tokensToReplace, List`1& tokensToDelete, List`1& loopProperties, List`1& condProps, JArray& arrayToForm, JObject& dictToForm, List`1& tokenToForm, List`1& tokensToAdd, Boolean& isLoop, Boolean& isBulk, JToken childToken)
   at JUST.JsonTransformer`1.RecursiveEvaluate(JToken& parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken)
   at JUST.JsonTransformer`1.LoopOperation(String propertyName, String arguments, IDictionary`2 parentArray, IDictionary`2 currentArrayToken, List`1& loopProperties, JArray& arrayToForm, JObject& dictToForm, JToken childToken)
   at JUST.JsonTransformer`1.ParsePropertyFunction(IDictionary`2 parentArray, IDictionary`2 currentArrayToken, List`1& loopProperties, List`1& condProps, JArray& arrayToForm, JObject& dictToForm, List`1& tokenToForm, List`1& tokensToAdd, Boolean& isLoop, JToken childToken, JProperty property, String functionName, String arguments)
   at JUST.JsonTransformer`1.ParseToken(JToken parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken, List`1& selectedTokens, Dictionary`2& tokensToReplace, List`1& tokensToDelete, List`1& loopProperties, List`1& condProps, JArray& arrayToForm, JObject& dictToForm, List`1& tokenToForm, List`1& tokensToAdd, Boolean& isLoop, Boolean& isBulk, JToken childToken)
   at JUST.JsonTransformer`1.RecursiveEvaluate(JToken& parentToken, IDictionary`2 parentArray, IDictionary`2 currentArrayToken)
   at JUST.JsonTransformer`1.Transform(JObject transformer, JToken input)
   at JUST.JsonTransformer`1.Transform(String transformerJson, JToken input)
   at JUST.JsonTransformer`1.Transform(String transformerJson, String inputJson)
   at FluidVsJust.Just() in C:\Users\vmello\source\repos\JustDotNetEventsExpansion\JustDotNetEventsExpansion\Program.cs:line 65
   at Program.Main() in C:\Users\vmello\source\repos\JustDotNetEventsExpansion\JustDotNetEventsExpansion\Program.cs:line 14

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
KeyNotFoundException: The given key 'affectedItems' was not present in the dictionary.
```

**Input JSON:**

```json
{
  "orderItems": [
    {
      "id": "1",
      "sku": "a"
    },
    {
      "id": "2",
      "sku": "b"
    },
    {
      "id": "3",
      "sku": "c"
    }
  ],
  "affectedItems": [
    1,
    2
  ],
  "test":  "abc" 
}
```

**Transformation Logic:**

```json
{
  "#loop($.affectedItems, affectedItems)": {
    "#loop($.orderItems, orderItems, root)": {
      "sku": "#currentvalueatpath($.sku)",
      "id": "#currentvalue(affectedItems)"
    }
  }
}
```

**Comment by Courela** [comment]
Be aware that alias are not trimmed, so the alias will be " affectedItem" and " root", spaces are allowed in alias.

**Comment by vmello-esw** [comment]
I removed the spaces, but it didn't seem to fix the problem.

```
{
  "#loop($.affectedItems,affectedItems)": {
    "#loop($.orderItems,orderItems,root)": {
      "sku": "#currentvalueatpath($.sku, orderItems)",
      "id": "#currentvalue(affectedItems)"
    }
  }
}
```

**Comment by Courela** [comment]
There's a bug if a loop, which refers to another alias, is added. Since that loop will contain 3 arguments (path, alias and reference alias) it will override alias already set with current one, not maintaining the ones that already exist. If new loop refers to previous loop, thus not requiring a reference alias, all works fine.
