### ISSUE TITLE
Exception on loop

### ISSUE THREAD

**Issue by tresoldigiorgio** [WorkMaze/JUST.net#94]
INPUT
```
{
 "array":[
{
   "resource":"Location",
    "number":"3"  
 },
   {
   "resource":"Organization",
    "number":"10"
 }
] 
}
```

TRANSFORMER
```
{
  "result_final":{
    "#loop($.array[?(@resource=='Location')])":{
     "result":"true"
    }
  }
}
```

EXCEPTION
```
System.ArgumentException: Can not add property result to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
   at Newtonsoft.Json.Linq.JObject.ValidateToken(JToken o, JToken existing)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at JUST.JsonTransformer.RecursiveEvaluate(JToken parentToken, String inputJson, JArray parentArray, JToken currentArrayToken, JUSTContext localContext)
   at JUST.JsonTransformer.RecursiveEvaluate(JToken parentToken, String inputJson, JArray parentArray, JToken currentArrayToken, JUSTContext localContext)
   at JUST.JsonTransformer.RecursiveEvaluate(JToken parentToken, String inputJson, JArray parentArray, JToken currentArrayToken, JUSTContext localContext)
   at JUST.JsonTransformer.Transform(JObject transformer, JToken input, JUSTContext localContext)
   at JUST.JsonTransformer.Transform(String transformerJson, JToken input, JUSTContext localContext)
   at JUST.JsonTransformer.Transform(String transformerJson, String inputJson, JUSTContext localContext)
```

Thanks

**Comment by mtdepippo** [comment]
@WorkMaze @Courela May I have any news about this PR?
